name       : handbrake
version    : 0.10.2
release    : 1
source     :
    - https://handbrake.fr/mirror/HandBrake-0.10.2.tar.bz2 : 4cc3828393b26a982dbe00febd700c5090d3443c1d45492e0b373e02da73c699
license    : GPL-2.0
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(libass)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - desktop-file-utils
    - pkgconfig(libbluray)
    - pkgconfig(libnotify)
    - pkgconfig(samplerate)
    - pkgconfig(libavcodec)
    - lame-devel
    - yasm
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    cd x86_64-solus-linux
    %make -j1
install    : |
    cd x86_64-solus-linux
    %make_install
