name       : handbrake
version    : 1.0.7
release    : 8
source     :
    - https://download.handbrake.fr/releases/1.0.7/HandBrake-1.0.7.tar.bz2 : ffdee112f0288f0146b965107956cd718408406b75db71c44d2188f5296e677f
license    : GPL-2.0
component  : multimedia.video
networking : yes
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libnotify)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - desktop-file-utils
    - bzip2-devel
    - lame-devel
    - yasm
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    cd x86_64-solus-linux
    %make -j1
install    : |
    cd x86_64-solus-linux
    %make_install
