name       : handbrake
version    : 1.0.3
release    : 5
source     :
    - https://handbrake.fr/mirror/HandBrake-1.0.3.tar.bz2 : 591fb489edd6146136f0a92f895c2098365f612ad308d5ff9dc83223ad73ed27
license    : GPL-2.0
component  : multimedia.video
networking : yes
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libnotify)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - desktop-file-utils
    - lame-devel
    - yasm
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    cd x86_64-solus-linux
    %make -j1
install    : |
    cd x86_64-solus-linux
    %make_install
