name       : handbrake
version    : 1.1.1
release    : 12
source     :
    - https://download.handbrake.fr/releases/1.1.1/HandBrake-1.1.1-source.tar.bz2 : e3390c5fd901fb06d72e29c62a63d373d5fb5b3467295d114d815ae7b78a9d7a
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
networking : yes
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libnotify)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - desktop-file-utils
    - bzip2-devel
    - lame-devel
    - yasm
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    cd x86_64-solus-linux
    %make
install    : |
    cd x86_64-solus-linux
    %make_install
