name       : handbrake
version    : 1.3.1
release    : 20
source     :
    - https://github.com/HandBrake/HandBrake/releases/download/1.3.1/HandBrake-1.3.1-source.tar.bz2 : c005de993af4123babbb60f7d12f6ff46fb7eea26ff0a3556034683901ce2c27
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
homepage   : https://handbrake.fr/
networking : yes
summary    : Video Converter
description: |
    HandBrake is a tool for converting video from nearly any format to a selection of modern, widely supported codecs.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(libbluray)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - bzip2-devel
    - lame-devel
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux --disable-numa
build      : |
    make -C x86_64-solus-linux
install    : |
    %make_install -C x86_64-solus-linux
