name       : handbrake
version    : 1.1.2
release    : 13
source     :
    - https://download.handbrake.fr/releases/1.1.2/HandBrake-1.1.2-source.tar.bz2 : ba9a4a90a7657720f04e4ba0a2880ed055be3bd855e99c0c13af944c3904de2e
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
networking : yes
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(libnotify)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(x264)
    - bzip2-devel
    - lame-devel
    - yasm
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    cd x86_64-solus-linux
    %make
install    : |
    cd x86_64-solus-linux
    %make_install
