name       : handbrake
version    : 1.4.1
release    : 29
source     :
    - https://github.com/HandBrake/HandBrake/releases/download/1.4.1/HandBrake-1.4.1-source.tar.bz2 : 39a0aecac8f26de1d88ccaca0a39dfca4af52029a792a78f93a42057a54c18f6
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
homepage   : https://handbrake.fr/
networking : yes
summary    : Video Converter
description: |
    HandBrake is a tool for converting video from nearly any format to a selection of modern, widely supported codecs.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(libdrm)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libva)
    - pkgconfig(opus)
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - bzip2-devel
    - lame-devel
setup      : |
    # configure doesn't like stuff
    ./configure \
        --build=x86_64-solus-linux \
        --enable-qsv \
        --enable-vce \
        --disable-numa \
        --harden \
        --prefix=/usr
build      : |
    %make -C x86_64-solus-linux
install    : |
    %make_install -C x86_64-solus-linux
