name       : handbrake
version    : 1.2.0
release    : 14
source     :
    - git|https://github.com/HandBrake/HandBrake.git : 1.2.0
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.video
networking : yes
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(speex)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(x264)
    - bzip2-devel
    - lame-devel
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    %make -C x86_64-solus-linux
install    : |
    %make_install -C  x86_64-solus-linux
