name       : handbrake
version    : 1.0.0
release    : 4
source     :
    - https://handbrake.fr/mirror/HandBrake-1.0.0.tar.bz2 : 15fb4593c70d75621212e4499f018c3c93d7ce39f1083bf527d4616ded0044c5
license    : GPL-2.0
component  : multimedia.video
networking : yes
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libnotify)
    - pkgconfig(opus)
    - pkgconfig(samplerate)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - desktop-file-utils
    - lame-devel
    - yasm
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    cd x86_64-solus-linux
    %make -j1
install    : |
    cd x86_64-solus-linux
    %make_install
