name       : handbrake
version    : 0.10.5
release    : 3
source     :
    - https://handbrake.fr/mirror/HandBrake-0.10.5.tar.bz2 : fb9230dd121b456f6829d1d25ac8bbf76e503b51c4efc70f0a7fd2bb8607e2f0
license    : GPL-2.0
component  : multimedia.video
summary    : Handbrake Video Converter
description: |
    Handbrake Video Converter
builddeps  :
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(freetype2)
    - pkgconfig(fribidi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libnotify)
    - pkgconfig(samplerate)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - desktop-file-utils
    - lame-devel
    - yasm
setup      : |
    # configure doesn't like stuff
    ./configure --prefix=/usr --build=x86_64-solus-linux
build      : |
    cd x86_64-solus-linux
    %make
install    : |
    cd x86_64-solus-linux
    %make_install
